version: 2.0
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo pip install --upgrade pip
            sudo pip install --upgrade awscli
      - checkout
      - run:
          name: deployment
          command: |
            # deploy production
            AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"                 \
            AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"         \
            DEPLOY_BUCKET="${DEPLOY_BUCKET}"                     \
            ./bin/deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
